### ISSUE TITLE
Allow possibility to filter on one or multiples tables

### ISSUE THREAD

**Issue by herewithme** [DvdGiessen/DBSR#3]
As on this script : 
https://github.com/interconnectit/Search-Replace-DB/blob/master/srdb.cli.php#L95

And only for CLI version ;)

**Comment by DvdGiessen** [comment]
Actually, the ability to filter on tables is already [in the code](https://github.com/DvdGiessen/DBSR/blob/master/DBSR.php#L291-L310), only it isn't supported by the CLI interface yet. I'll see if I can add it any time soon, or feel free to submit a pull request. :)
