### ISSUE TITLE
return 255 on mysql ipv6 only host

### ISSUE THREAD

**Issue by pierrehenrymuller** [DvdGiessen/DBSR#5]
Hi,
When I use compiled dbsr cli on a mysql ipv6 only host, I get a 255 return code without warning or message.
There is the command : 
dbsr-cli --output text  --user user --password pass --database dbname --extensive-search true --charset utf8 -- www.website.com test.website.com

I have try to add host option with ::1 or ip6-localhost which correspond to ::1 but without success.

PDO support ipv6 only mysql host so I don't know why it's don't work if you have an idea for helping you to improve the code.

Thanks

**Comment by DvdGiessen** [comment]
Hm, just a guess, but can you try with the IPv6-address enclosed in square brackets, as per RFC2732? I suspect the colons in the IPv6 notation may be confused for a separator indicating the port number.

**Comment by pierrehenrymuller** [comment]
I have found the problem.
With args --extensive-search true --charset utf8 no error was display.
When I remove this args I discover an error, on this mariadb only server, php5-mysqlnd was not installed but php5-cli was present.
After installing package, dbsr works fine on ipv6 only host :)
Maybe additional args disable verbose on error?
