### ISSUE TITLE
unserialize(): Error at offset 203 of 1226 bytes

### ISSUE THREAD

**Issue by sebastienserre** [DvdGiessen/DBSR#8]
Hello,

I'm using your tool on my localhost and have this error:
"unserialize(): Error at offset 203 of 1226 bytes"

ddo you know what's happen?

**Comment by thierrypigot** [comment]
I have the same problem :(

**Comment by iouston** [comment]
And me too

**Comment by arnolito** [comment]
Idem

**Comment by netagence** [comment]
Same here, interested in getting updates. In case it helps, result was:

Results
RESULT occurence(s) found and replaced.
Restart
**unserialize(): Error at offset 554 of 579 bytes**

Thanks.

**Comment by DvdGiessen** [comment]
I've finally had some time to look into it. The initial problem turned out to be the regexes which handle broken serialized data did not properly supporting namespace in the serialized object name. Resolved that and am no longer able to reproduce the error, thus closing this issue. Fixes are available in [v2.1.1](https://github.com/DvdGiessen/DBSR/releases/tag/2.1.1). If you still have problems, let me know. :)

**Comment by fabienlege** [comment]
Always the same problem with extended search ...

**Comment by DvdGiessen** [comment]
Hi @fabienlege!

What are you using extended search for, are you running search-and-replace on some special serialized values?

Which version of PHP are you running and can you perhaps share the full error message and/or an example I can use to reproduce the issue? Thanks!

**Comment by fabienlege** [comment]
I use extended search to migrate wordpress website. I exécute a search and
replace to replace domain name in database

**Comment by DvdGiessen** [comment]
When replacing a domain name in Wordpress, you probably don't need to use the "extended search" option. DBSR is a lot faster without it, and when replacing a domain name (or any text without non-text characters in it) it doesn't make a difference. See also the note about using "extensive search" in [the readme](https://github.com/DvdGiessen/DBSR#readme).

If you can share more details about the problem, such as the full error message you're getting or ideally a example which I can use to reproduce the issue, I might be able to look into it further.
