### ISSUE TITLE
Syntax error on step 3

### ISSUE THREAD

**Issue by fabienlege** [DvdGiessen/DBSR#9]
I've this error when trying to start the proccess (after click on "Start" button on step 3) : 
```syntax error, unexpected '\' (T_NS_SEPARATOR), expecting '{'```

I try to search this string : 
```src="/sites/default```

and replacing by :
```src="/es/sites/default```

PHP v 7.0

**Comment by DvdGiessen** [comment]
@fabienlege I've tried to reproduce this but so far no luck. Which version of DBSR are you using?

**Comment by fabienlege** [comment]
I've just cloned this repository today, it's the 2.1.1 version (GUI 2.0.4)
Here a screenshot of the error. that's occur just after clicking "start" button
![capture d ecran 2017-08-07 a 15 55 56](https://user-images.githubusercontent.com/2045814/29029803-2bb3e480-7b89-11e7-8b4f-296b0955b8af.jpg)

**Comment by DvdGiessen** [comment]
@fabienlege I believe I have found the cause: serialized namespaced classes. I've commited a fix in 9831b167545e62da1534add827be84c28aec9f5a.

Could you try pulling from the repository and checking if that latest version resolves your issue?

**Comment by fabienlege** [comment]
After update, i confirm it working for me ;)
Thanks !
